apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-controller-otp-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-platform-controller-otp-service@sha256:6081d72429826f8624bc1b34f01ca1aee66f3c2fc18dea112652d34e28626c15
        name: container-image
        resources: {}
status: {}
