apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-controller-otp-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-platform-controller-otp-service@sha256:37b2a951fd2644520f77352b5c177477bcf2bf0eb27d66061aa970aede84b7a3
        name: container-image
        resources: {}
status: {}
