apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-controller-otp-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-controller-otp-service
    app.kubernetes.io/part-of: multi-arch-controller
  name: multi-platform-controllerjlah
spec:
  port:
    targetPort: 8443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: multi-platform-controller-otp-service
    weight: 100
status: {}
