apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-controller-otp-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-controller-otp-service
    app.kubernetes.io/part-of: multi-arch-controller
  name: multi-platform-controller-otp-service
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-platform-controller-otp-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-platform-controller-otp-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-platform-controller-otp-service@sha256:c5c07bb6adee235805dae4d53e107a756685791d90c869bb421b60d4c5edb753
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
