apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacktask-image-multi-platform-controller
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/hacktask-image-multi-platform-controller@sha256:d733531a07ede2e73500c500a33cdaf78332db146ffdc23d3c1a71b253a734b6
        name: container-image
        resources: {}
status: {}
