apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacktask-image-multi-platform-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/hacktask-image-multi-platform-controller@sha256:50b0745f503cb73f3441bddd74bc89d6cdd177fa8a376112065bef9f4cd15e79
        name: container-image
        resources: {}
status: {}
