apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacktask-image-multi-platform-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacktask-image-multi-platform-controller
    app.kubernetes.io/part-of: multi-arch-controller
  name: hacktask-image-multi-platxdkl
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hacktask-image-multi-platform-controller
    weight: 100
status: {}
