apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacktask-image-multi-platform-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacktask-image-multi-platform-controller
    app.kubernetes.io/part-of: multi-arch-controller
  name: hacktask-image-multi-platform-controller
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hacktask-image-multi-platform-controller
status:
  loadBalancer: {}
