apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-arch-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-arch-controller@sha256:5c14baecf6bb5ab707d65a9f984b3b86f93b7757c53f7b5843092356fc221271
        name: container-image
        resources: {}
status: {}
