apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-arch-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-arch-controller@sha256:296c38a2326f725ff0dc18e9c2ec6f6cca5cb1d30d15b07a9a1d12869b206a87
        name: container-image
        resources: {}
status: {}
