apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-arch-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/multi-arch-controller/multi-arch-controller@sha256:e48a79c3a0546e70a6eef7905796b0f897156bbe1889ebaecd519562b04e488c
        name: container-image
        resources: {}
status: {}
